### PR TITLE
Add Progressbar Wista

### PR DESCRIPTION
**Pull request by pivinx1**
I did some stuff to add Wista.
Just be aware that I might have broken something or Wista might work improperly. Also left a few notes.

### CODE REVIEW

**Comment by pivinx1** [comment]
hol up, I forgot something

**Comment by pivinx1** [comment]
should be okay, go on, pull it

**Comment by BurningInfern0** [comment]
the voices

**Comment by BurningInfern0** [comment]
okayayyyy y y looks good my  ma n

**Pull request merged**
