### PR TITLE
Might be good to add a saveguard

### PR DESCRIPTION
**Pull request by 5jiji**
If the language has been changed manually to the setting.pcsf, to not make it crash at boot

If there is no need to add, please don't close this pull, i will add the encryption of the save file

### CODE REVIEW

**Comment by BurningInfern0** [comment]
sure

**Review by markverb1 — COMMENTED** [review]
i guess yeah

**Comment by zai-tm** [comment]
5jiji when will you understand that encrypting the save is pointless

**Comment by luihum** [comment]
Shut up zai it at least makes it so cheaters have to do stuff

**Pull request merged**
