### PR TITLE
Add a settings menu

### PR DESCRIPTION
**Pull request by 5jiji**
Hello, i am creating a setting menu for the game for having multiple choice for the visual of the game or other thing.
This menu is still a WIP and i will work on it for some time

- [x] Added the menu to the beginning menu
- [x] Change the logic behind the beginning menu (to make the setting menu, obviously)
- [x] Added the save system of the settings
- [x] Add the first setting (will be a test one, it will be a leftover for you to see how the settings work)

And, obviously:
- [x] Verified for bug

If BurningInfern0 say no to this, then i will stop coding for the setting menu

### CODE REVIEW

**Comment by zai-tm** [comment]
hello admins

**Comment by 5jiji** [comment]
do you really need to do this ?

**Comment by 5jiji** [comment]
The save system have bug, it doesn't work at all
i don't have time for update it today so tomorrow i will fix it (if i find a way)

**Comment by 5jiji** [comment]
Poll request unlock

**Comment by RealMCoded** [comment]
> do you really need to do this ?

\*in zai voice* yes

**Comment by setapdede** [comment]
e

**Comment by 5jiji** [comment]
Stop bombing my pull request! Please!

**Comment by setapdede** [comment]
funny thing, no

**Comment by zai-tm** [comment]
`no`

**Comment by luihum** [comment]
@everyon stop

**Comment by zai-tm** [comment]
so uh, nice day today

**Comment by RealMCoded** [comment]
my emails are flooded thx

**Comment by setapdede** [comment]
how are you feeling zai

**Comment by zai-tm** [comment]
not god

**Comment by leapofazzam123** [comment]
t

**Pull request merged**
