### PR TITLE
Simplified catch code, 

### PR DESCRIPTION
**Pull request by abnormalhare**
here it is, in all of its glory.
made `progressbar` a list instead of an int (for orange and blue (and later grey, pink, and glitch))
removed extra variables (`bar2`/`progressbar2`)

Edit: update to newest branch (removal of `settingsdict`

### CODE REVIEW

**Comment by poggers16** [comment]
sire, it has conficts

**Review by poggers16 — CHANGES_REQUESTED** [review]
fucking conflicts11!1!1!1

**Comment by abnormalhare** [comment]
Yeah, there was conflicts because burning wont stop updating the game before accepting my pr

**Comment by abnormalhare** [comment]
Not anymore

**Review by 5jiji — CHANGES_REQUESTED** [review]
Test your code before sending a poll

Screenshot_20220426_140935

**Comment by abnormalhare** [comment]
Fixed 5jiji's bug and boot.py bug

**Comment by poggers16** [comment]
haha i made score system!!!!!

**Comment by abnormalhare** [comment]
> haha i made score system!!!!!

Ok, if you want, you can pr that code to my dev branch and i can merge it into this pr

**Comment by 5jiji** [comment]
Pull closed because it can poses problems for the future, the code is untested and unorganized.

**Comment by abnormalhare** [comment]
What problems

**Comment by 5jiji** [comment]
https://www.youtube.com/watch?v=Sz61GToBLLM 
This one for example (sorry for the low framerate i record my screen with VLC)

**Comment by abnormalhare** [comment]
I never worked with that, that isnt a bug i made... and i dont even see a bug?

**Comment by 5jiji** [comment]
If you go in settings it goes directly in the boot menu without shutdown

**Comment by 5jiji** [comment]
lem me see if it's on the original

**Comment by abnormalhare** [comment]
Can you suggest a change and reopen it

**Comment by setapdede** [comment]
🍿

**Comment by 5jiji** [comment]
@setapdede Shut up

**Comment by setapdede** [comment]
no >:)

**Comment by abnormalhare** [comment]
It'd be a dream if I could get 1 pr in

**Comment by luihum** [comment]
Trolled

**Comment by zai-tm** [comment]
> It'd be a dream if I could get 1 pr in

your dreams are too big

**Comment by abnormalhare** [comment]
You're just mean :(

**Comment by abnormalhare** [comment]
This pr isnt like last time, im not even changing anything about how the game really works, just fixing bugs

**Pull request closed without merging**
