### PR TITLE
Rich Library Update

### PR DESCRIPTION
**Pull request by BurningInfern0**
Replaced the outdated ```Termcolor``` dependency with the better ```Rich``` library.
Thank you to **setapdede** for telling me about Rich!

### CODE REVIEW

**Comment by BurningInfern0** [comment]
looks good to me, fam. wow you're really good at coding god dayum!!! go work at microsoft or something

**Comment by RealMCoded** [comment]
damnnnnnnnnnnnnnnnnnnnnnnnn this some CLEAN AS FUCK code

**Comment by abnormalhare** [comment]
Bruh

**Comment by setapdede** [comment]
progres?

**Pull request merged**
